// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneBookApp.Services.Contacts.DbContexts;

#nullable disable

namespace PhoneBookApp.Services.Contacts.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20230127115924_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhoneBookApp.Services.Contacts.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff9e6a8e-c1cb-4d9f-8a8e-57feaf87f07b"),
                            FirstName = "Eric",
                            LastName = "Elliot",
                            PhoneNumber = "222-555-6575"
                        },
                        new
                        {
                            Id = new Guid("5f7b62b0-02f3-4ca0-b2cc-a12ede1cc04c"),
                            FirstName = "Steve",
                            LastName = "Jobs",
                            PhoneNumber = "220-454-6754"
                        },
                        new
                        {
                            Id = new Guid("f4716960-8641-4008-a0f9-dae69db71a86"),
                            FirstName = "Fred",
                            LastName = "Allen",
                            PhoneNumber = "210-657-9886"
                        },
                        new
                        {
                            Id = new Guid("c417164d-b9a6-4d68-b1fa-61710657cb1f"),
                            FirstName = "Steve",
                            LastName = "Wozniak",
                            PhoneNumber = "343-675-8786"
                        },
                        new
                        {
                            Id = new Guid("68c4171b-5940-4ce9-8983-9c33bb0df524"),
                            FirstName = "Bill",
                            LastName = "Gates",
                            PhoneNumber = "343-654-9688"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
